### ISSUE TITLE
MC+ shows the most recent email in a thread and not the first unread

### ISSUE THREAD

**Issue by Daenyth** [AndersSahlin/MailCheckerPlus#1]
Perhaps this should be configurable, but it should default to displaying the first unread message (and following messages when expanded) rather than the most recent in thread. If you're in a thread with more than one person you can end up missing replies in the middle.

**Comment by AndersSahlin** [comment]
This has to do with the way I fetch the content of the mail. It's more tricky to find the first unread item rather than just the most recent. I think the feed (which generates the summary) also just shows the most recent item.

**Comment by Daenyth** [comment]
Perhaps you could cache the id of the thread & message and then not update the preview window with subsequent messages until the message id is marked as read?
