### ISSUE TITLE
Popup window eats global keybindings

### ISSUE THREAD

**Issue by Daenyth** [AndersSahlin/MailCheckerPlus#2]
When the preview window is active, it eats all keybindings, preventing everything else from acting on them. Hitting Fn+foo for example has no effect until the preview is closed

**Comment by AndersSahlin** [comment]
I'm not sure, but this could be an issue with Chrome and not the extension itself. Does it happen on other extensions pop-ups?

**Comment by Daenyth** [comment]
I think it also happens with voice checker, which has a similar popup.
