### ISSUE TITLE
Action Buttons do not work on Classic

### ISSUE THREAD

**Issue by Bijan-A** [AndersSahlin/MailCheckerPlus#22]
I am having the same problem as https://github.com/AndersSahlin/MailCheckerPlus/issues/21 but I am having it with the classic version. Any chance you could tell me what to change on mailaccount.class.js?

**Comment by AndersSahlin** [comment]
Change

var matches = this.responseText.match(/\?at=([^"]+)/);

To

var matches = this.responseText.match(/\at=([^"]+)/);

**Comment by Bijan-A** [comment]
Is there anyway you can update the classic version? I am able to change it on my PC and laptop but not my CR48 because I do not have access to the file (easily). A lot of people were complaining that their action buttons do not work and they do not like the new version of the Mail Checker.
