### ISSUE TITLE
No longer visible in Chrome Web Store

### ISSUE THREAD

**Issue by aceat64** [AndersSahlin/MailCheckerPlus#25]
This extension is no longer available in Google's Chrome Web Store, was it removed by Anders or by Google?

**Comment by bessx** [comment]
Noticed this too, i think he was trying to update it to 1.2.4, and deleted it...

Maybe it was google, but i'm not so sure...

**Comment by petersaints** [comment]
http://code.google.com/p/mail-checker-plus/issues/detail?id=44&colspec=ID%20Type%20Status%20Modified%20Priority%20Milestone%20Owner%20Summary

http://code.google.com/p/mail-checker-plus/issues/detail?id=42&colspec=ID%20Type%20Status%20Modified%20Priority%20Milestone%20Owner%20Summary

http://code.google.com/p/mail-checker-plus/issues/detail?id=43&colspec=ID%20Type%20Status%20Modified%20Priority%20Milestone%20Owner%20Summary

http://code.google.com/p/mail-checker-plus/issues/detail?id=40&colspec=ID%20Type%20Status%20Modified%20Priority%20Milestone%20Owner%20Summary

Same problem reported on Google Code.

There are currently two work arounds:

#1

Until this extension comes back to the Chrome Web Store, you can do the following to manually install it in Chrome:
1. Go to: https://github.com/AndersSahlin/MailCheckerPlus/downloads
2. Click on either the "Download as zip" or "Download as tar.gz" button (most people will probably click on the zip option).
3. Unzip the file that you downloaded in step 2.
4. In Chrome, click on the Wrench menu, select Tools, and click on Extensions.
5. Place a check mark next to "Developer mode."
6. Click on the "Load unpacked extension" button at the top.
7. Navigate to where you unzipped the extension and click OK.

After completing these steps, the extension will be installed in Chrome and you can configure the options. This was found in issue 43, but I just typed out the details steps. These steps assume that you are running the latest version of Google Chrome.
(You can also easily pack the extension with a very similar process)
#2 (by me)
I packed the extension and made it available: http://home.pedro.albuquerques.net/dist/GoogleMailCheckerPlus.crx

Both are just work arounsd. Please... as soon as the addon gets back to the Webstore reinstall that version. This version is UNOFFICIAL, it's not my property and will receive no support nor updates.

**Comment by liuyxpp** [comment]
I love this extension. Please come back to the Google web store. Other gmail checkers are either lack of functions or ugly.

**Comment by brodkin** [comment]
The author has been silent on this issue, and I'm willing to venture a guess why...

Anyone with the most recent packaged version of the plugin installed will find that they have additional ads on youtube.com and yahoo.com, as added by the plugin.

You can read more about this here:

http://code.google.com/p/mail-checker-plus/issues/detail?id=46&colspec=ID%20Type%20Status%20Modified%20Priority%20Milestone%20Owner%20Summary

I'm guessing that someone reported him and Google removed the plugin.

Anybody want to maintain a fork?

**Comment by aceat64** [comment]
I've created a fork of the 1.2.4 branch, I'm very new to Chrome extensions so I can't offer any guarantees that this will work or that I will be able to maintain it long term.

https://github.com/aceat64/MailCheckerMinus

**Comment by aceat64** [comment]
The new fork (Mail Checker Minus) is now in the Chrome Web Store.

https://chrome.google.com/webstore/detail/ebojakelgejdogaleoeoaadjpefeifen

**Comment by brodkin** [comment]
Wow, you're a quick one, aren't ya?

**Comment by hanynowsky** [comment]
You called it actually, Minus :) You broke the ideology henceforth!!! 
Seriously speaking, this extension is just wonderful for the Gmail users. The other extensions are just useless (Ugly interface, very basic functionalities...).
Crap! instead of blocking it Google had to warn. And if they are really blocking it, they should provide a similar or better extension instead of the crappy one in chrome store.

What coding language is used? Javascript?

**Comment by hanynowsky** [comment]
Since, the code here is Open source and clean ( no advertisment scripts). Anyone created a reliable fork?

**Comment by brodkin** [comment]
I have a fork in progress, but it isn't done yet.  As long as you keep that
in mind...

You're welcome to install it in developer mode and try it out!

On Sun, Jan 15, 2012 at 6:29 PM, Hanyn <
reply@reply.github.com

**Comment by hanynowsky** [comment]
Great thanks. Brodkin!

**Comment by bessx** [comment]
https://chrome.google.com/webstore/detail/ebojakelgejdogaleoeoaadjpefeifen
 is a great fork, already in place.

**Comment by jbtibor** [comment]
Yet another fork:
https://github.com/jbtibor/MailCheckerPlus

Store:
https://chrome.google.com/webstore/detail/hjnhldiccejnglnjfppmbcnkfmkhihcb
