### ISSUE TITLE
Tooltip for "sendPageLinkTitle" undefined

### ISSUE THREAD

**Issue by Hebo** [AndersSahlin/MailCheckerPlus#3]
The alt-text is missing for the send link to page button (displays as undefined). This is due to a lack of a definition in the language array for 'sendPageLinkTitle'.

Adding the line 
        "sendPageLinkTitle" : "Send link"
in i18n.js, after line 92 solves this issue for the English language

**Comment by AndersSahlin** [comment]
Fixed. This string also needs to be translated, though. The best thing would be if the i18n-system defaulted to the English language if some entries are missing.

**Comment by Hebo** [comment]
Yea, I'm seeing if I can get something like that set up.

**Comment by Hebo** [comment]
Fixed at Cev/MailCheckerPlus@abdd6e62d94212a2640d62bdba8b7cf642830f18

**Comment by AndersSahlin** [comment]
Nice, thanks! :)
