### ISSUE TITLE
Selected language not being displayed as selected in options page

### ISSUE THREAD

**Issue by mbrevda** [AndersSahlin/MailCheckerPlus#4]
Even if you save your requested language, and although the plug in respects that setting, it nevertheless doesn't show your language as selected in the options page. See here for more info: http://goo.gl/Ad5X

Proposed solution:
Change line 298 of options.html (in version 1.1.7) to:
langSel.add(new Option(languages[i].what, languages[i].id, (languages[i].id == 'en'), (languages[i].id == localStorage["gc_language"])), languages[i].id);

**Comment by AndersSahlin** [comment]
Already fixed.

**Comment by mbrevda** [comment]
Oh, now I see how you did it. Not that there is really a performance penalty for something so simple, but would you agree that it would be better to utilize the same method(Option()), instead of adding another line of code?

**Comment by AndersSahlin** [comment]
Agreed :)

**Comment by mbrevda** [comment]
haha. On another note, I was wondering about having some sort of IMAP js library, so that there is no need to poll, and yet to get real time updates?

**Comment by AndersSahlin** [comment]
Feel free to experiment if you want. When I looked into IMAP support it came down to the lack of integration in Gmail (how do you link IMAP mail to Gmail thread id's, for instance?).

**Comment by mbrevda** [comment]
You can always poll once you KNOW there is new mail...
