### ISSUE TITLE
Clicking new message in notification does not bring up actual message

### ISSUE THREAD

**Issue by mdmower** [AndersSahlin/MailCheckerPlus#5]
Version 1.1.8 with the extension ID fix for blank desktop notifications (http://chrome.desc.se/forum/viewtopic.php?pid=846#p846)
Chrome 5.0.375.55 beta

When a new email arrives, I can click on the subject in desktop notification to bring me right to the message.  If I click on the Google Mail Checker Plus icon, then click on the subject, my GMail inbox is opened and the message is marked read, but the actual message does not open.

**Comment by AndersSahlin** [comment]
No idea why this happens. Both links use the same function to open mail.

**Comment by mdmower** [comment]
In testing this just now, it did work as expected.  I have had this issue many times in the past though, so there must be certain circumstances during which it occurs.  If you like this thread can be closed and later I will start a new Issue when I identify the cause.

**Comment by AndersSahlin** [comment]
Great. :)
