### ISSUE TITLE
Clicking icon does not recognize when GMail Inbox is already open

### ISSUE THREAD

**Issue by mdmower** [AndersSahlin/MailCheckerPlus#6]
Version 1.1.8 with the extension ID fix for blank desktop notifications (http://chrome.desc.se/forum/viewtopic.php?pid=846#p846)
Chrome 5.0.375.55 beta

When I click on the Google Mail Checker Plus icon (no new emails), a new GMail tab is opened, even if one already exists.  It would be nice if this extension could recognize when a GMail inbox is open, and activate that tab instead of creating a new one.

**Comment by AndersSahlin** [comment]
This feature is already implemented, and should work as proposed. Any special settings that might interfere?

**Comment by mdmower** [comment]
This issue is easily reproducible for me.  Inbox open, no new emails, click mail icon and new tab opens.

Google Mail Checker Plus Options:
 Show desktop notifications, Archive marks as read, Always use SSL, Open compose in tab

Other extensions loaded: Xmarks Bookmarks Sync, RSS Live Links, Notifier for Google Wave, Google Calendar Checker w/ Popup, Forecastfox Weather, AdBlock, Browser Button for AdBlock

I just disabled all extensions and checked again.  Still same behavior.

**Comment by AndersSahlin** [comment]
Very strange, I cannot reproduce this issue. 

I have a tab with the following URL opened: https://mail.google.com/mail/#inbox

Clicking the icon takes me to that tab. I'm using 1.1.7, could you see if the error is present there as well?

**Comment by mdmower** [comment]
Just tested 1.1.7 and that version works correctly.

**Comment by AndersSahlin** [comment]
Found the issue and fixed it. Thanks!

**Comment by mdmower** [comment]
Tested your commit and it does seem to work properly now.
